<?php
/** @package Reloading::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("BrushMap.php");

/**
 * BrushDAO provides object-oriented access to the Brush table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Reloading::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class BrushDAO extends Phreezable
{
	/** @var int */
	public $BrushId;

	/** @var float */
	public $Caliber;

	/** @var string */
	public $Thread;

	/** @var string */
	public $Material;

	/** @var int */
	public $Handle;


	/**
	 * Returns the foreign object based on the value of Handle
	 * @return Handle
	 */
	public function GetHandleHandle()
	{
		return $this->_phreezer->GetManyToOne($this, "Brush_ibfk_1");
	}


}
?>