<?php
/** @package Reloading::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("CasingMap.php");

/**
 * CasingDAO provides object-oriented access to the Casing table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Reloading::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class CasingDAO extends Phreezable
{
	/** @var int */
	public $CasingId;

	/** @var string */
	public $CasingName;

	/** @var float */
	public $Caliber;

	/** @var float */
	public $WallThickness;

	/** @var int */
	public $UseExpectancy;

	/** @var int */
	public $Amount;

	/** @var float */
	public $CostPerCasing;

	/** @var char */
	public $PocketSize;


	/**
	 * Returns a dataset of Recipe objects with matching Casing
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetCasingRecipes($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "Recipe_ibfk_2", $criteria);
	}


}
?>