<?php
/** @package Reloading::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("DieMap.php");

/**
 * DieDAO provides object-oriented access to the Die table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Reloading::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class DieDAO extends Phreezable
{
	/** @var int */
	public $DieId;

	/** @var char */
	public $Grade;

	/** @var string */
	public $Manufacture;

	/** @var string */
	public $DieType;

	/** @var float */
	public $Caliber;

	/** @var int */
	public $Press;


	/**
	 * Returns the foreign object based on the value of Press
	 * @return Press
	 */
	public function GetPressPress()
	{
		return $this->_phreezer->GetManyToOne($this, "Die_ibfk_1");
	}


}
?>