<?php
/** @package Reloading::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("PowderMap.php");

/**
 * PowderDAO provides object-oriented access to the Powder table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Reloading::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class PowderDAO extends Phreezable
{
	/** @var int */
	public $PowderId;

	/** @var string */
	public $Name;

	/** @var string */
	public $PowderType;

	/** @var string */
	public $BurnRate;

	/** @var float */
	public $QuantityInGrains;

	/** @var float */
	public $CostPerGrain;


	/**
	 * Returns a dataset of Recipe objects with matching Powder
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetPowderRecipes($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "Recipe_ibfk_1", $criteria);
	}


}
?>