<?php
/** @package Reloading::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("PressMap.php");

/**
 * PressDAO provides object-oriented access to the Press table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Reloading::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class PressDAO extends Phreezable
{
	/** @var int */
	public $PressId;

	/** @var string */
	public $Manufacture;

	/** @var int */
	public $ProductionRate;

	/** @var char */
	public $PressType;

	/** @var string */
	public $Thread;


	/**
	 * Returns a dataset of Die objects with matching Press
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetPressDies($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "Die_ibfk_1", $criteria);
	}


}
?>